server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: db1 # ����Ĭ�����ݿ�
      datasource:
        db1: # ����Դ1����
          url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2: # ����Դ2����
          url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        db3: # ����Դ3����
          url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
#  autoconfigure:
#    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # ȥ��druid����
#    DruidDataSourceAutoConfigure��ע��һ��DataSourceWrapper�������ԭ����spring.datasource���� url, username, password �ȡ�
#    ��̬����Դ URL ���������� dynamic �£������Ҫ�ų�������ᱨ���ų���ʽ�����֣�һ�������������ļ��ų�������һ�ֿ�������Ŀ�������ų���